obj-$(CONFIG_NET_SOCIONEXT_OGMA)  := ogma.o
ogma-objs := ogma_basic_access.o \
		ogma_basic_access.o \
		ogma_desc_ring_access.o \
		ogma_misc.o \
		pfdep_linux.o \
		ogma_netdev.o \
		ogma_gmac_access.o \
		ogma_driver.o \
		netsec_dring.o \
		netsec_drv.o



