obj-$(CONFIG_SND_MB8AC0300_PCM) += mb8ac0300_pcm.o
obj-$(CONFIG_SND_SOC_MB86S27_AK4642) += mb86s27_ak4642.o
obj-$(CONFIG_SND_SOC_MB86S70_HDMI) +=  f_hdmi_card.o
obj-$(CONFIG_SND_SOC_MB86S70_HDMI_DAI) += f_hdmi_dai.o

