#define IRQ_ARM_GLOBAL_TIMER		27
#define IRQ_ARM_FIQ			28
#define IRQ_ARM_PRIVATE_TIMER		29
#define IRQ_ARM_WDT			30
#define IRQ_ARM_IRQ			31

#define IRQ_OFFSET			32

#define IRQ_COMMTX0			(0 + IRQ_OFFSET)
#define IRQ_COMMRX0			(1 + IRQ_OFFSET)
#define IRQ_COMMTX1			(2 + IRQ_OFFSET)
#define IRQ_COMMRX1			(3 + IRQ_OFFSET)

#define IRQ_L2CCINTR			(8 + IRQ_OFFSET)
#define IRQ_TIMINT0			(9 + IRQ_OFFSET)
#define IRQ_TIMINT1			(10 + IRQ_OFFSET)
#define IRQ_WDOGINT			(11 + IRQ_OFFSET)
#define IRQ_UART0			(12 + IRQ_OFFSET)
#define IRQ_UART1			(13 + IRQ_OFFSET)
#define IRQ_MEMCTRLINT			(14 + IRQ_OFFSET)
#define IRQ_RELC_INT			(15 + IRQ_OFFSET)

#define IRQ_XDMAC0			(16 + IRQ_OFFSET)
#define IRQ_XDMAC1			(17 + IRQ_OFFSET)
#define IRQ_XDMAC2			(18 + IRQ_OFFSET)
#define IRQ_XDMAC3			(19 + IRQ_OFFSET)
#define IRQ_XDMAC4			(20 + IRQ_OFFSET)
#define IRQ_XDMAC5			(21 + IRQ_OFFSET)
#define IRQ_XDMAC6			(22 + IRQ_OFFSET)
#define IRQ_XDMAC7			(23 + IRQ_OFFSET)

#define IRQ_EXTINT0			(24 + IRQ_OFFSET)
#define IRQ_EXTINT1			(25 + IRQ_OFFSET)
#define IRQ_EXTINT2			(26 + IRQ_OFFSET)
#define IRQ_EXTINT3			(27 + IRQ_OFFSET)
#define IRQ_EXTINT4			(28 + IRQ_OFFSET)
#define IRQ_EXTINT5			(29 + IRQ_OFFSET)
#define IRQ_EXTINT6			(30 + IRQ_OFFSET)
#define IRQ_EXTINT7			(31 + IRQ_OFFSET)
#define IRQ_EXTINT8			(32 + IRQ_OFFSET)
#define IRQ_EXTINT9			(33 + IRQ_OFFSET)
#define IRQ_EXTINT10			(34 + IRQ_OFFSET)
#define IRQ_EXTINT11			(35 + IRQ_OFFSET)
#define IRQ_EXTINT12			(36 + IRQ_OFFSET)
#define IRQ_EXTINT13			(37 + IRQ_OFFSET)
#define IRQ_EXTINT14			(38 + IRQ_OFFSET)
#define IRQ_EXTINT15			(39 + IRQ_OFFSET)

#define IRQ_IPCUINT0			(40 + IRQ_OFFSET)
#define IRQ_IPCUINT1			(41 + IRQ_OFFSET)

#define IRQ_EXTINT16			(112 + IRQ_OFFSET)
#define IRQ_EXTINT17			(113 + IRQ_OFFSET)
#define IRQ_EXTINT18			(114 + IRQ_OFFSET)
#define IRQ_EXTINT19			(115 + IRQ_OFFSET)
#define IRQ_EXTINT20			(116 + IRQ_OFFSET)
#define IRQ_EXTINT21			(117 + IRQ_OFFSET)
#define IRQ_EXTINT22			(118 + IRQ_OFFSET)
#define IRQ_EXTINT23			(119 + IRQ_OFFSET)
#define IRQ_EXTINT24			(120 + IRQ_OFFSET)
#define IRQ_EXTINT25			(121 + IRQ_OFFSET)
#define IRQ_EXTINT26			(122 + IRQ_OFFSET)
#define IRQ_EXTINT27			(123 + IRQ_OFFSET)
#define IRQ_EXTINT28			(124 + IRQ_OFFSET)
#define IRQ_EXTINT29			(125 + IRQ_OFFSET)
#define IRQ_EXTINT30			(126 + IRQ_OFFSET)
#define IRQ_EXTINT31			(127 + IRQ_OFFSET)

#define MB8AC0300_NR_IRQS		256     /* (32 + 128) */
#define MB8AC0300_IRQ_OFFSET		32
#ifndef CONFIG_SPARSE_IRQ
#define NR_IRQS				MB8AC0300_NR_IRQS
#endif
