# Generic MAILBOX API

obj-$(CONFIG_MAILBOX)		+= mailbox.o

obj-$(CONFIG_MAILBOX_TEST)	+= mailbox-test.o

obj-$(CONFIG_ARM_MHU)	+= arm_mhu.o

obj-$(CONFIG_MBOX_F_IPCU)	+= f_ipcu.o ipcu_client.o
obj-$(CONFIG_IPCU_USERAPI)	+= snrtos_ipcu.o

obj-$(CONFIG_PL320_MBOX)	+= pl320-ipc.o

obj-$(CONFIG_OMAP2PLUS_MBOX)	+= omap-mailbox.o

obj-$(CONFIG_PCC)		+= pcc.o

obj-$(CONFIG_ALTERA_MBOX)	+= mailbox-altera.o

obj-$(CONFIG_BCM2835_MBOX)	+= bcm2835-mailbox.o

obj-$(CONFIG_STI_MBOX)		+= mailbox-sti.o
